name: flutter_developers_guide
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    provider: ^5.0.0
    flutter_markdown: ^0.6.1
    http: ^0.13.3
    camera: ^0.8.1
    video_player: ^2.1.1
    audioplayers: ^0.19.0
    share_plus: ^2.1.2
    url_launcher: ^6.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/videos/
        - assets/audios/
        # add individual directories containing files, don't remove it after adding it once and seeing working as it caches the data
        - assets/markdowns/architecture/
        - assets/markdowns/flutter_fundamentals/
        - assets/markdowns/lifecycle/
        - assets/markdowns/navigation_routing/
        - assets/markdowns/state_management/

        - assets/markdowns/ui_manipulation/
        - assets/markdowns/ui_manipulation/colors_backgrounds/
        - assets/markdowns/ui_manipulation/dimensions_constraints/
        - assets/markdowns/ui_manipulation/effects/
        - assets/markdowns/ui_manipulation/interactive_behaviours/
        - assets/markdowns/ui_manipulation/layout/
        - assets/markdowns/ui_manipulation/responsive_adaptive_layout/
        - assets/markdowns/ui_manipulation/spacing/
        - assets/markdowns/ui_manipulation/media/

        - assets/markdowns/widget_catalog/
        - assets/markdowns/widget_catalog/accessibility/
        - assets/markdowns/widget_catalog/animation_motion/
        - assets/markdowns/widget_catalog/assets_icons_images/
        - assets/markdowns/widget_catalog/async/
        - assets/markdowns/widget_catalog/cupertino/
        - assets/markdowns/widget_catalog/input/
        - assets/markdowns/widget_catalog/interactive/
        - assets/markdowns/widget_catalog/layout/
        - assets/markdowns/widget_catalog/material/
        - assets/markdowns/widget_catalog/painting_effects/
        - assets/markdowns/widget_catalog/scrolling/
        - assets/markdowns/widget_catalog/styling/
        - assets/markdowns/widget_catalog/text/

        - assets/markdowns/native_device_features/

        - assets/markdowns/rest_api/

        - assets/markdowns/supporting_classes_enums/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Montserrat
          fonts:
              - asset: assets/fonts/montserrat/Montserrat-Light.ttf
              - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
              - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
              - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
              - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - family: Roboto Slab
          fonts:
              - asset: assets/fonts/roboto_slab/RobotoSlab-Light.ttf
              - asset: assets/fonts/roboto_slab/RobotoSlab-Regular.ttf
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
